name: PR Comment

description: Manages a bot comment on a Pull Request

inputs:
  github-token:
    description: The GitHub token to use
    default: ${{ github.token }}
    required: false
  comment-identifier:
    description: A unique string that identifies the comment
    required: true
  comment-body:
    description: The body of the comment
    required: true

runs:
  using: composite
  steps:
    - uses: actions/github-script@v7
      env:
        # Capture the stdout/stderr in env vars to get them from process in the script to avoid unescaped quote issues
        commentIdentifier: ${{ inputs.comment-identifier }}
        commentBody: ${{ inputs.comment-body }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const prComment = require('${{ github.action_path }}/pr_comment.js')
          prComment(github, context, `${process.env.commentIdentifier}`, `${process.env.commentBody}`)
